### ISSUE TITLE
`src/test/java` sometimes compiled in the `compile` task

### ISSUE THREAD

**Issue by DevCharly** [cbeust/kobalt#216] opened 2016-05-31 08:31 UTC
Ok, this one is strange. Have some projects with tests (`src/test/java` folders) and Kobalt compiles them in the `compile` task (with errors; that's why I discovered it).

Took me some time until I found out (in the debugger) that varying source directories are the reason. Usually have only "src", but sometimes "src/main/java".

Some info to reproduce the issue:

Build.kt:
```
val p1 = project {
	name = "p1"
	directory = name
	sourceDirectories = hashSetOf( "src" )
}

val p2 = project(p1) {
	name = "p2"
	directory = name
}
```

Files:
```
p1/src/p1.java
p2/src/main/java/p2.java
p2/src/test/java/p2test.java
```

The resulting javac command line, which includes p2test.java:
`javac -d p2\kobaltBuild\classes -classpath D:\Projects\kobalt-sandbox\p2\kobaltBuild\classes;p1\kobaltBuild\classes p2\src\main\java\p2.java p2\src\test\java\p2test.java`

I had a breakpoint at JvmCompilerPlugin.createCompilerActionInfo() and found out that the parameter sourceDirectories contains `[src]` when first invoked for p1, but on second call for p2 it is `[src, src\main\java, src\main\java]`. `src` should be not there for p2 because files.findRecursively() then searches `p2/src` and finds p2test.java

**Comment by cbeust** [comment] 2016-06-01 21:44
This should be fixed now.

**Comment by DevCharly** [comment] 2016-06-02 16:02
Sorry, but it still does not work here in 0.799 :cry:

**Comment by cbeust** [comment] 2016-06-02 16:10
What compilation line are you seeing?

Mine:

```
Calling kotlinc -module-name project-klaxon -d ./kobaltBuild/classes -classpath /Users/beust/.kobalt/repository/org/jetbrains/kotlin/kotlin-runtime/1.0.0/kotlin-runtime-1.0.0.jar:/Users/beust/.kobalt/repository/org/jetbrains/kotlin/kotlin-stdlib/1.0.0/kotlin-stdlib-1.0.0.jar -no-stdlib ./src/main/java ./src/main/kotlin
```

I see no test directories on the classpath.

**Comment by DevCharly** [comment] 2016-06-02 16:14
No, it is not about the classpath (this was another issue).

I have java files from `src/test` in javac. `p2\src\test\java\p2test.java` in the above example.

**Comment by cbeust** [comment] 2016-06-02 16:25
Can you attach a zip file of your project, or maybe make it available on github? Easier for me to reproduce.

**Comment by DevCharly** [comment] 2016-06-02 16:34
sure: [kobalt-sandbox.zip](https://github.com/cbeust/kobalt/files/296066/kobalt-sandbox.zip)

**Comment by cbeust** [comment] 2016-06-02 16:43
Thanks, I can reproduce the problem.

**Comment by cbeust** [comment] 2016-06-02 16:46
This is happening because of:

```
    sourceDirectories = hashSetOf( "src" )
```

Kobalt then finds all the source files recursively under that directory, which includes `src/test`.

**Comment by DevCharly** [comment] 2016-06-02 16:50
Yes, I know. I should have pointed out this better in my report...

**Comment by cbeust** [comment] 2016-06-02 16:50
So there is no bug, correct? Ok to close this issue?

**Comment by DevCharly** [comment] 2016-06-02 16:52
No, this is a bug!

**Comment by DevCharly** [comment] 2016-06-02 16:55
Source directories of one project should not used in other projects.

**Comment by cbeust** [comment] 2016-06-02 16:57
But it's not doing that, it's only using directories under `p2` to compile the project "p2":

```
javac -d p2/kobaltBuild/classes -classpath p1/kobaltBuild/classes p2/src/main/java/p2.java p2/src/test/java/p2test.javap2/src/test/java/p2test.java:4: error: <identifier> expected
asdfasdfsadf
            ^
p2/src/test/java/p2test.java:5: error: reached end of file while parsing

```

**Comment by DevCharly** [comment] 2016-06-02 17:00
Well, not on the javac command line, but before when invoking `files.findRecursively()` to find .java files.

`p2test.java` should not on the javac command line

**Comment by cbeust** [comment] 2016-06-02 17:01
But it should since you specified `src` as a source directory for `p2`, right?

**Comment by cbeust** [comment] 2016-06-02 17:02
What I see:

`p1`:

```
javac -d p1/kobaltBuild/classes p1/src/main/java/p1.java
```

`p2`:

```
javac -d p2/kobaltBuild/classes -classpath p1/kobaltBuild/classes p2/src/main/java/p2.java p2/src/test/java/p2test.java
```

I see nothing wrong in this.

**Comment by DevCharly** [comment] 2016-06-02 17:04
No. Source directory of `p1` is `src`, but for `p2` it is `src/main/java`

**Comment by cbeust** [comment] 2016-06-02 17:57
Oh got it! Bug indeed.

**Closed** 2016-06-02 18:09 UTC

**Comment by cbeust** [comment] 2016-06-02 18:13
Should be fixed in latest.

**Comment by DevCharly** [comment] 2016-06-02 18:35
Yes, it works. Thx :+1:
