### ISSUE TITLE
Plugins fatJar are full of unneeded dependencies (documentation & bug)

### ISSUE THREAD

**Issue by ethauvin** [cbeust/kobalt#432] opened 2017-04-26 22:35 UTC
Per the docs:

```
    dependencies {
        compile("org.apache.maven:maven-settings-builder:3.3.9")
        compile("com.beust:$kobaltDependency:")
    }

    dependenciesTest {
        compile("org.testng:testng:")

    }
```
![2017-04-26 15_21_08-c__users_erik_desktop_tmp2_kobalt-maven-local-0 5 3 jar_com_](https://cloud.githubusercontent.com/assets/705618/25459709/7164627a-2a94-11e7-8722-f3ce4fad7297.png)

Looks like it's including the `kobalt-api` dependencies, which does make sense. The solution, which was not available until recently, is to use:

```
    dependencies {
        compile("org.apache.maven:maven-settings-builder:3.3.9")
        compileOnly("com.beust:$kobaltDependency:")
}
```
![2017-04-26 15_30_37-k__kotlin_kobalt-maven-local_kobaltbuild_libs_kobalt-maven-local-0 5 3 jar_](https://cloud.githubusercontent.com/assets/705618/25459885/5f37cf46-2a95-11e7-8862-3e31cd67b59e.png)
Looks better, except for the `kotlin` directory.

**Comment by cbeust** [comment] 2017-04-27 18:43
Ok to close this issues since we established in Slack that `kotlin` is `kotlin-stdlib`, which is pulled by `kobalt-plugin-api`?

**Comment by ethauvin** [comment] 2017-04-27 22:00
I don't think so. `compileOnly` excludes the `kobalt-plugin-api` and its dependencies. It works, everything is gone from `fatJar`, except for the `kotlin-stdlib` in the `kotlin` directory.

**Comment by cbeust** [comment] 2017-04-27 22:35
[Working as intended:](https://github.com/cbeust/kobalt/blob/master/src/main/kotlin/com/beust/kobalt/plugin/kotlin/KotlinPlugin.kt#L103-L105)

```
            // All Kotlin projects automatically get the Kotlin runtime added to their class path
            listOf(kotlinJarFiles.stdlib, kotlinJarFiles.runtime)
                    .map { FileDependency(it.absolutePath) }
```

Closing per our Slack conversation.

**Closed by cbeust** 2017-04-27 22:35 UTC
