### ISSUE TITLE
Kobalt does not seem to use standard proxy settings

### ISSUE THREAD

**Issue by pysaumont** [cbeust/kobalt#307] opened 2016-12-01 15:36 UTC
Hi,

Running Kobalt behind a proxy with `http_proxy` correctly configured does not work. Error message is `Warning: couldn't download http://beust.com/kobalt/kobalt-0.905.zip`.

`wget http://beust.com/kobalt/kobalt-0.905.zip` works fine to download the zip file. After copying it in `~/.kobalt/wrapper/dist/`, Kobalt starts and throws an exception: 

```
Couldn't retrieve releases from github: connect timed out
java.net.SocketTimeoutException: connect timed out
```

Is there a specific way to configure proxy access?

**Comment by cbeust** [comment] 2016-12-01 17:32
I had to take a look at the code and it looks like proxy support is only working for artifact downloading but not downloading Kobalt itself.

Proxies are defined in your `~/.config/kobalt/settings.xml`:

```
<kobaltSettings>
    <proxies>
      <proxy>
        <host>...</host>
        <port>...</port>
      </proxy>
    </proxies>
</kobaltSettings>
```

Aether will correctly pick up this proxy, however, the download for Kobalt itself needs to be patched at this location:

https://github.com/cbeust/kobalt/blob/master/modules/wrapper/src/main/java/com/beust/kobalt/wrapper/Main.java#L367

Would you be interested in fixing this?

**Comment by pysaumont** [comment] 2016-12-01 21:35
I will have a look at it.

**Comment by pysaumont** [comment] 2016-12-05 10:23
The change was quite easy, but I couldn't find a way to build Kobalt, since the Idea project uses Kobalt to build itself, and Kobalt does work before it is built with the change (chicken and egg!). I manage to find another machine not behind a proxy and built it, with version 0.906, but it still does not work on the original machine. When starting with 

kobaltw --init kotlin

it downloads kobalt-0905 and runs this version. Is there a way to disable downloading the older version?

I tried changing the 0.905 references to 0.906 (in kobalt-wrapper-properties and wrapperVersion.txt) and replaced kobalt-wrapper.jar with the new version. With these changes, the message was:

vxl20046 kotlin_projects/kotlinTest $ ./kobaltw test
[Wrapper error] *** No file to download. Server replied HTTP code: 404
[Wrapper error] *** No file to download. Server replied HTTP code: 404
[Wrapper error] *** No file to download. Server replied HTTP code: 404
Exception in thread "main" java.io.FileNotFoundException: ~/.kobalt/wrapper/dist/kobalt-0.906.zip (No such file or directory)

I installed manually the kobalt-0.906.zip file in ~/.kobalt/wrapper/dist and then got 

vxl20046 kotlin_projects/kotlinTest $ ./kobaltw test
[Wrapper error] *** No file to download. Server replied HTTP code: 404
            _  __          _               _   _   
           | |/ /   ___   | |__     __ _  | | | |_ 
           | ' /   / _ \  | '_ \   / _` | | | | __|
           | . \  | (_) | | |_) | | (_| | | | | |_ 
           |_|\_\  \___/  |_.__/   \__,_| |_|  \__|  0.905

Couldn't retrieve releases from github: connect timed out
java.net.SocketTimeoutException: connect timed out
...
ERROR Invalid classpath: couldn't find /local/kotlin_projects/kotlinTest/DOESNOTEXIST org.jetbrains.kotlin:kotlin-stdlib:jar:1.0.4

As it seems it is still using 0.905, I removed 0.905 from ~/.kobalt/wrapper/dist, so that only 0.906 is present. Now, the message is 

vxl20046 kotlin_projects/kotlinTest $ ./kobaltw test
            _  __          _               _   _   
           | |/ /   ___   | |__     __ _  | | | |_ 
           | ' /   / _ \  | '_ \   / _` | | | | __|
           | . \  | (_) | | |_) | | (_| | | | | |_ 
           |_|\_\  \___/  |_.__/   \__,_| |_|  \__|  0.905

Couldn't retrieve releases from github: connect timed out
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
       ...
Couldn't find ~/.kobalt/wrapper/dist/kobalt-0.905/kobalt/wrapper/kobalt-0.905.jar, using
  ~/kotlin/kobalt/kobaltBuild/classes ~/kotlin/kobalt/modules/kobalt-plugin-api/kobaltBuild/classes ~/kotlin/kobalt/modules/wrapper/kobaltBuild/classes ~/.kobalt/wrapper/dist/kobalt-0.904/kobalt/wrapper/kobalt-0.904.jar

Any idea about what to try next?

**Comment by cbeust** [comment] 2016-12-05 20:22
Hi Pierre-Yves,

Have you read the instructions here:  http://beust.com/kobalt/contributing/index.html

This should help you set up your environment to have a working version of Kobalt (basically, you point it to a nonexistent version so that it will pick up the classes you just compiled instead).

Let me know if this is not enough to get you started and I'll fix the documentation.

Thanks for your efforts, hope you don't give up!

**Comment by pysaumont** [comment] 2016-12-06 14:44
Yes, of course, I have read these instructions. I have made the change and I have built Kobalt using version number 0.906, as I explained in the message above. By the way, I found the version number in 

    kobalt/src/main/resources/kobalt.properties
    kobalt/kobalt/wrapper/kobalt-wrapper.properties

Does the second one needs to be changed?

The problem is that the version I compiled on the machine without a proxy don't work (as can be seen in my previous message). On the machine behind a proxy, I could not download the dependencies. I managed to get all dependencies by hand (by copying the Kobalt cache from the other machine.) Now, with Kotlin 1.1-M03-release-IJ2016.3-2, I get a compile error:

    Error:Kotlin: [Internal Error] java.lang.IllegalStateException: SimpleTypeImpl should not be created for error type: ErrorScope{Error scope for class <ERROR CLASS: kotlin.reflect.KClass> ...

So I had to revert to Kotlin 1.0.5, with which I have the following error:

    Error:Android Source Generator: [kobalt] Android SDK is not specified

Can't Kobalt be used without Android SDK?

I installed Android SDK with some difficulties and now, I have a new error:

    Error:Android Source Generator: [kobalt] AndroidManifest.xml file not found

although this file is present in 

    /src/test/resources/projects/templates/androidJava/src/main/AndroidManifest.xml

**Comment by pysaumont** [comment] 2016-12-06 18:01
I have found that an Android configuration had been automatically detected and added by IntelliJ. I have removed it. Then I had an error in file KotlinCompiler.kt:

    Error:(107, 29) Kotlin: Object must be declared abstract or implement abstract member public abstract fun clear(): Unit defined in org.jetbrains.kotlin.cli.common.messages.MessageCollector

So I added the following implementation:

    val collector = object : MessageCollector {
    override fun clear() {
            throw UnsupportedOperationException("not implemented") //To change body of created functions use File | Settings | File Templates.
        }

Now, I get this error when running Kobalt:

    Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: --log2

So I removed the parameter. Now, Kobalt starts (displaying SLF4J error messages about multiple configuration found) and then an exception:

    ERROR: Exception while analyzing expression at (236,9) in /tmp/kobalt4488759207352877444.kt:
    Files.copy(from,
                to,
                StandardCopyOption.REPLACE_EXISTING)

    java.lang.NoSuchMethodError: org.jetbrains.kotlin.utils.FunctionsKt.getDO_NOTHING_3()Lkotlin/jvm/functions/Function3;

My conclusion is that it is probably not possible (or at least extremely tedious) to build Kobalt without Kobalt already working! So I don't see any solution... Maybe trying to install a proxy on the machine with direct access.

**Comment by cbeust** [comment] 2016-12-06 18:03
It is definitely possible but the errors you are seeing make me think there
is an environment problem, probably a discrepancy between the Kotlin
compiler version you have installed and the one Kobalt uses.

In the meantime, maybe you can send me your patch and I can integrate it
manually?


-- 
Cédric

**Comment by pysaumont** [comment] 2016-12-06 21:45
OK. I have made a pull request.

**Comment by pysaumont** [comment] 2016-12-08 15:30
It's better now, with version 0.906. However, it was still not working. First, I had to add module dependencies for Build.kt on modules kobalt and kobalt-plugin-api, as well as a dependency on maven-model. Without these dependencies, it works only once (with a dependency on Kobalt-0.905 which is broken after the first execution of the `kotlin:assemble` task).

With these changes, it worked but it does not download anything. It seems (from looking at the sources) that the config file example on your site is not correct. Here is a working configuration:

```
<kobaltSettings>
    <proxies>
      <proxy>
        <type>http</type>
        <host>my-proxy.com</host>
        <port>8000</port>
      </proxy>
      <proxy>
        <type>https</type>
        <host>my-proxy.com</host>
        <port>8000</port>
      </proxy>
    </proxies>
</kobaltSettings>
```
Without the <type> elements, it does not work. 

Another problem is that when running `kobaltw --init`, it creates a build file with the following dependency:

    dependenciesTest {
        compile("org.testng:testng:")
    }

This does not work. Manually adding the version fixes the problem.

**Comment by pysaumont** [comment] 2016-12-08 16:48
I have now changed the `Main.java` class to use the HTTP proxy from the Kobalt setting file. I had to add a dependency on `kobalt-plugin-api` for this. I don't know if this is OK. I will create a pull request with this change. It seems to work, since I receive 

    [Wrapper error] *** No file to download. Server replied HTTP code: 404

this is probably due to the fact that I am using a new version number. But the 404 error code means I have reached the server through the proxy.

**Comment by cbeust** [comment] 2016-12-08 17:43
No, `Main.java` needs to be a totally independent project that doesn't depend on anything. This is important in order to keep `kobalt-wrapper.jar` as small as possible (since it gets checked in with projects).

So for `Main.java` to parse `~/.config/kobalt/settings.xml`, we can either do it properly (with an XML parser) or just do it quick and dirty: parse the config file line by line and pick the first host/port line you can find. I'd rather do it properly and ideally without adding any dependencies (use the standard XML parser).

What didn't work about the `org.testng:testng:` dependency? This should download the latest version of TestNG, did you get an error?

**Comment by cbeust** [comment] 2016-12-08 17:45
> Without the elements, it does not work.

Ah, are you saying `<type>` is mandatory? That's quite possible indeed.

FYI, the code that instantiates the proxy from this file is in `KobaltSettingsXml.kt:91`. I'll update the doc.

**Comment by cbeust** [comment] 2016-12-08 17:48
About your other points: did you install the Kobalt IDEA plug-in? Once you do that, you can just sync your project and it should automatically set up all your modules and libraries based on `kobalt/src/Build.kt`. You should not have to do any of this manually.

**Comment by pysaumont** [comment] 2016-12-09 08:01
1) TestNG: I reinstalled everything from scratch and did not see the problem again.

2) &lt;type>: Yes, it appears to be mandatory, so I guess we need to declare to proxies, one for HTTP and one for HTTPS

3) Kobalt IDEA plug-in: I must be missing something about IntelliJ. Don't know what you mean by "sync". But I found I can get the effect you describe by closing and reopening the project. I don't know why IntelliJ does not detect that it is a Kobalt project on first opening. There is still a little problem: running the kobalt:assemble task don't trigger the kobalt-wrapper:assemble task. Is it normal? It results in the following error:

    ERROR Error: File should exist: ./modules/wrapper/kobaltBuild/libs/kobalt-wrapper.jar

So I have to manually run kobalt-wrapper:assemble first (although kobalt:assemble triggers kobalt-wrapper:compile.

4) Parsing config file without module dependency: I'll be doing that.

**Comment by cbeust** [comment] 2016-12-09 17:12
That third point is really weird, all the `assemble` tasks should be run, obviously.

Can you reproduce this from the command line or is it an IDEA-only thing?

**Comment by pysaumont** [comment] 2016-12-10 08:34
It worked fine the first time I ran Kobalt from the console except that it ended with an "unknown error" (but the zip file had been created). After running kobalt:clean, kobalt:assemble ran without error. And after that, there were no longer any problem with IntelliJ. 

I downloaded kobalt-master once more and opened it as w new IntelliJ project, and it worked fine.

The only minor problem that is left with IntelliJ is that when opening the project for the first time, it is not recognized as a Kobalt project, and syncing does change anything. I have to close the project an reopen it to make it work. Not a big deal.

**Comment by cbeust** [comment] 2016-12-10 15:10
Look in the IDEA messages, there should be a message telling you a Kobalt
project has been detected and to click on a link to import it (or to show
the actual balloon that will give you that option).

-- 
Cédric

**Comment by pysaumont** [comment] 2016-12-13 21:34
It works on some machines, not on others (without closing an reopening the project).

Do you have an idea of when the new version will be available on your site?

**Comment by cbeust** [comment] 2016-12-13 21:44
The new version of Kobalt, 0.906? It's been available just a few hours
after I merged your change.

What functionality are you looking for?

**Comment by pysaumont** [comment] 2016-12-13 22:08
I thought it would have an incremented version number. No problem!

Le mar. 13 déc. 2016 à 22:44, Cedric Beust <notifications@github.com> a
écrit :

**Comment by cbeust** [comment] 2016-12-13 22:10
It does, I bumped it to 0.906. As far as I know, there hasn't been new
changes since then.

In doubt, just do `./kobaltw update`.

-- 
Cédric

**Closed** 2017-01-05 19:44 UTC
